/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.VentaController;
import com.itextpdf.text.DocumentException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author douglas.alarcon
 */
public class VistaVenta extends javax.swing.JFrame {

    /**
     * Creates new form vistaVenta
     */
    public VistaVenta() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public JComboBox<String> getCbxPlanes() {
        return cbxPlanes;
    }

    public ButtonGroup getBtgDescuentos() {
        return btgDescuentos;
    }

    public JRadioButton getRbtCincoPorCiento() {
        return rbtCincoPorCiento;
    }

    public JRadioButton getRbtNoAplica() {
        return rbtNoAplica;
    }

    public JRadioButton getRdbDiezPorCiento() {
        return rdbDiezPorCiento;
    }

    public JTextField getTxtValor() {
        return txtValor;
    }

    public JTextField getTxtValorDescuento() {
        return txtValorDescuento;
    }

    public JTextField getTxtValorTotal() {
        return txtValorTotal;
    }

    public JTable getGrilla() {
        return grilla;
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDescuentos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxPlanes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        rbtCincoPorCiento = new javax.swing.JRadioButton();
        rbtNoAplica = new javax.swing.JRadioButton();
        rdbDiezPorCiento = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValorDescuento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        botonCalcular = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        btnGernerarReporte = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoAdministrarVentas.PNG"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 50));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volverAtras.PNG"))); // NOI18N
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel1.setText("Plan:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 22));

        cbxPlanes.setEditable(true);
        cbxPlanes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPlanesActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 82, 134, 20));

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Descuentos:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        btgDescuentos.add(rbtCincoPorCiento);
        rbtCincoPorCiento.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        rbtCincoPorCiento.setText("5% ");
        rbtCincoPorCiento.setContentAreaFilled(false);
        rbtCincoPorCiento.setFocusable(false);
        jPanel1.add(rbtCincoPorCiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, 30));

        btgDescuentos.add(rbtNoAplica);
        rbtNoAplica.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        rbtNoAplica.setSelected(true);
        rbtNoAplica.setText("No aplica");
        rbtNoAplica.setContentAreaFilled(false);
        rbtNoAplica.setFocusable(false);
        rbtNoAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNoAplicaActionPerformed(evt);
            }
        });
        jPanel1.add(rbtNoAplica, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 80, 30));

        btgDescuentos.add(rdbDiezPorCiento);
        rdbDiezPorCiento.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        rdbDiezPorCiento.setText("10%");
        rdbDiezPorCiento.setContentAreaFilled(false);
        rdbDiezPorCiento.setFocusPainted(false);
        jPanel1.add(rdbDiezPorCiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 30));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel8.setText("Descripción:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 22));

        txtDescripcion.setEditable(false);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 370, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel5.setText("Valor:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 20));

        txtValor.setEditable(false);
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 80, 22));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel3.setText("Valor descuento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, 40));

        txtValorDescuento.setEditable(false);
        jPanel1.add(txtValorDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 94, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel4.setText("Valor total");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, 40));

        txtValorTotal.setEditable(false);
        jPanel1.add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 85, -1));

        botonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoConsulta.PNG"))); // NOI18N
        botonCalcular.setBorderPainted(false);
        botonCalcular.setContentAreaFilled(false);
        botonCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonCalcular.setFocusPainted(false);
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(botonCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 100, 70));

        btnPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoPagar.PNG"))); // NOI18N
        btnPagar.setBorderPainted(false);
        btnPagar.setContentAreaFilled(false);
        btnPagar.setFocusPainted(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 94, 71));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoCancelar.PNG"))); // NOI18N
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 72));

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plan", "Valor", "% Descuento", "Descuento", "Total"
            }
        ));
        jScrollPane1.setViewportView(grilla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 546, 227));

        btnGernerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoCrearPDF.PNG"))); // NOI18N
        btnGernerarReporte.setBorderPainted(false);
        btnGernerarReporte.setContentAreaFilled(false);
        btnGernerarReporte.setFocusPainted(false);
        btnGernerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGernerarReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnGernerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 131, 84));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoAbrir.PNG"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, 88));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPlanesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPlanesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        VentaController.botonSalir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGernerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGernerarReporteActionPerformed
        try {
            VentaController.botonGenerarReporte();
        } catch (IOException | DocumentException ex) {
            Logger.getLogger(VistaVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGernerarReporteActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        VentaController.botonPagar();
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        VentaController.botonCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        VentaController.botonCalcular();
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    VentaController.botonAbrirReporte("Reporte");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbtNoAplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNoAplicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNoAplicaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCalcular;
    private javax.swing.ButtonGroup btgDescuentos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JToggleButton btnGernerarReporte;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxPlanes;
    private javax.swing.JTable grilla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtCincoPorCiento;
    private javax.swing.JRadioButton rbtNoAplica;
    private javax.swing.JRadioButton rdbDiezPorCiento;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtValorDescuento;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
